name: cloudera
services:
  cdh5:
    image: ghcr.io/stevenqcly/cloudera-cdh5:cdh5-v2
    ports:
      - 10000:10000
      - 10002:10002
      - 11000:11000
      - 18080:18080
      - 2181:2181
      - 50070:50070
      - 60010:60010
      - 60030:60030
      - 8088:8088
      - 8888:8888
    privileged: true
    volumes:
      - /data/run:/run
      - /data/tmp:/tmp
